[workspace]
resolver = "2"
members = [
  "crates/nzbg",
  "crates/nzbg-scheduler",
  "crates/nzbg-core",
  "crates/nzbg-nzb",
  "crates/nzbg-nntp",
  "crates/nzbg-yenc",
  "crates/nzbg-queue",
  "crates/nzbg-postproc",
  "crates/nzbg-server",
  "crates/nzbg-config",
]
