[package]
name = "nzbg-config"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
dirs = "5.0"
nzbg-core = { path = "../nzbg-core" }
thiserror = "2.0"

[dev-dependencies]
tempfile = "3.11"
