[package]
name = "nzbg-nzb"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
flate2 = "1.1"
quick-xml = "0.37"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"

[dev-dependencies]
serde_json = "1.0"
